### PR TITLE
Upgrade Cake to 0.17.0

### PR DESCRIPTION
**Pull request by devlead**
Cake 0.18.0 will requires at least version 0.16.x to work.

### CODE REVIEW

**Comment by kharlamov** [comment]
@Redth, could we please get some eyes on this?

**Comment by kitforbes** [comment]
The main drawback of open source. It would be good if the Cake team could be added as collaborators so that they can take over if needed.

**Comment by gep13** [comment]
>@kitforbes said...
The main drawback of open source. It would be good if the Cake team could be added as collaborators so that they can take over if needed.

We would never "take over" a project, however, we do encourage that addin's be moved into the cake-contrib organisation:

https://github.com/cake-contrib

so that more people can help out with issues like this.  This was documented here:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

and an update was provided regarding it here:

http://www.gep13.co.uk/blog/an-update-on-cake-contrib-user-and-organisation

We, as the Cake Team, will never force an addin maintainer to do anything that they don't want to do.

**Comment by Redth** [comment]
Sorry folks, on vacation so limited access here. Will try and publish this shortly

**Pull request merged**
