### PR TITLE
Upgrade Cake to v0.18

### PR DESCRIPTION
**Pull request by rdeago**
Because it's about time.

### CODE REVIEW

**Comment by TomPallister** [comment]
👍

**Comment by DixonDs** [comment]
Once 0.18.0 is released it is important to get this merged, since now Cake 0.18.0 doesn't work with the latest Cake.Json release: http://cakebuild.net/blog/2017/03/cake-v0.18.0-released

**Comment by moswald** [comment]
Any word on this one? It's blocking our ability to move to VS2017.

**Comment by gep13** [comment]
>@DixonDs said...
Once 0.18.0 is released it is important to get this merged, since now Cake 0.18.0 doesn't work with the latest Cake.Json

As a minimum, this PR is all that is required:

https://github.com/Redth/Cake.Json/pull/14

>@moswald said...
It's blocking our ability to move to VS2017.

Nothing should be currently blocking you.  You should be able to simply pin the version of Cake that you are using to 0.17.0, and your builds should continue to work.  Unless there is something specific in 0.18.0 that you are relying on.

**Comment by moswald** [comment]
The cake script only works by relying on 0.18 features like the `MSBuildToolVersion.VS2017` enum. --While we could go back to 0.17 and then fix up the build server and some dev machines to work properly, it's a lot easier to just change that one line.

**Comment by gep13** [comment]
>@moswald said...
The cake script only works by relying on 0.18 features like the MSBuildToolVersion.VS2017 enum. --While we could go back to 0.17 and then fix up the build server and some dev machines to work properly, it's a lot easier to just change that one line.

Gotcha. Yip, that makes sense.

**Comment by kitforbes** [comment]
@rdeago, you are missing a change in the nuspec file. You need to update the version of Cake.Core to match.

**Comment by rdeago** [comment]
@kitforbes thanks for pointing out what I forgot.
On second thought I removed the dependency completely, as per commit c0ff8d0bec444973a876fb23aa48b97813d5b6be in origin.
Now it's up to @Redth, apparently. I remain at disposal if there's something I can do to speed up merging.

**Comment by rdeago** [comment]
Maybe it's just me being a noob, but is there anything I can do to have this PR merged?

I see there are conflicts, but to solve them I should revert to Cake 0.17.1, which would hardly "solve" anything.

**Comment by Redth** [comment]
Hey @rdeago i definitely appreciate the PR, however I've already fixed these things up in master manually, so I'm just going to close this one out without merging.

Technically I'm using Cake 0.17 instead of 0.18 as a dependency, but that's to fulfill the requirements of using > 0.16 and still keeping some backwards compatibility with older versions of cake we have running in CI at this point.

Cheers!

**Comment by rdeago** [comment]
That's fine, thanks @Redth!

**Pull request closed without merging**
